repos:
  - repo: local
    hooks:
      - id: secrets-hunter
        name: Secrets-in-Code Hunter
        entry: python scanner.py --repo ./test_files
        language: system
        types: [python, yaml, json]